import type { Recipe, RawMaterial, RecipeFamily } from './types';

export const INITIAL_FAMILIES: RecipeFamily[] = [
  { id: '1', name: 'Galletas' },
  { id: '2', name: 'Pasteles' },
  { id: '3', name: 'Panes' },
  { id: '4', name: 'Masas Fritas' },
  { id: '5', name: 'Bollería' },
  { id: '6', name: 'Mousses y Cremosos' },
  { id: '7', name: 'Tartas' },
  { id: '8', name: 'Bizcochos' },
  { id: '9', name: 'Cremas y Rellenos' },
  { id: '10', name: 'Postres Clásicos' },
  { id: '11', name: 'Helados y Sorbetes' },
  { id: '12', name: 'Macarons' },
  { id: '13', name: 'Petit Fours'},
  { id: '14', name: 'Ganaches' },
];

export const INITIAL_RAW_MATERIALS: RawMaterial[] = [
  { id: '1', name: 'Harina de Trigo (Todo Uso)', price: 1.5, packageSize: 1000, unit: 'g' },
  { id: '2', name: 'Azúcar Blanca', price: 1.2, packageSize: 1000, unit: 'g' },
  { id: '3', name: 'Mantequilla sin Sal', price: 3.5, packageSize: 250, unit: 'g' },
  { id: '4', name: 'Huevo (Tamaño L)', price: 2.0, packageSize: 12, unit: 'unit' },
  { id: '5', name: 'Chocolate Negro 70%', price: 4.0, packageSize: 200, unit: 'g' },
  { id: '6', name: 'Leche Entera', price: 1.0, packageSize: 1000, unit: 'ml' },
  { id: '7', name: 'Extracto de Vainilla', price: 5.0, packageSize: 50, unit: 'ml' },
  { id: '8', name: 'Nata 35% MG', price: 2.5, packageSize: 1000, unit: 'ml' },
  { id: '9', name: 'Gelatina en hojas (2g)', price: 3.0, packageSize: 12, unit: 'unit' },
  { id: '10', name: 'Chocolate Blanco 35%', price: 5.0, packageSize: 250, unit: 'g' },
  { id: '11', name: 'Chocolate con Leche 40%', price: 4.5, packageSize: 250, unit: 'g' },
  { id: '12', name: 'Cacao en Polvo sin azúcar', price: 2.8, packageSize: 250, unit: 'g' },
  { id: '13', name: 'Almendra Molida', price: 4.0, packageSize: 250, unit: 'g' },
  { id: '14', name: 'Azúcar Glas', price: 1.8, packageSize: 500, unit: 'g' },
  { id: '15', name: 'Levadura Fresca', price: 1.0, packageSize: 25, unit: 'g' },
  { id: '16', name: 'Harina de Fuerza', price: 1.6, packageSize: 1000, unit: 'g' },
  { id: '17', name: 'Sal Fina', price: 0.5, packageSize: 1000, unit: 'g' },
  { id: '18', name: 'Puré de Frambuesa', price: 6.0, packageSize: 500, unit: 'g' },
  { id: '19', name: 'Puré de Maracuyá', price: 7.0, packageSize: 500, unit: 'g' },
  { id: '20', name: 'Pectina NH', price: 10.0, packageSize: 50, unit: 'g' },
  { id: '21', name: 'Glucosa Líquida', price: 3.0, packageSize: 375, unit: 'g' },
  { id: '22', name: 'Azúcar Invertido', price: 3.5, packageSize: 375, unit: 'g' },
  { id: '23', name: 'Yemas de Huevo Pasteurizadas', price: 2.5, packageSize: 250, unit: 'g' },
  { id: '24', name: 'Claras de Huevo Pasteurizadas', price: 2.2, packageSize: 250, unit: 'g' },
  { id: '25', name: 'Limón', price: 1.5, packageSize: 4, unit: 'unit' },
  { id: '26', name: 'Aceite de Girasol', price: 2.0, packageSize: 1000, unit: 'ml' },
  { id: '27', name: 'Maicena (Almidón de maíz)', price: 1.2, packageSize: 500, unit: 'g' },
  { id: '28', name: 'Pistacho Molido', price: 8.0, packageSize: 150, unit: 'g' },
  { id: '29', name: 'Café Soluble', price: 3.0, packageSize: 100, unit: 'g' },
  { id: '30', name: 'Queso Crema', price: 2.2, packageSize: 300, unit: 'g' },
  { id: '31', name: 'Puré de Fresa', price: 6.0, packageSize: 500, unit: 'g' },
  { id: '32', name: 'Albahaca Fresca', price: 1.5, packageSize: 20, unit: 'g' },
  { id: '33', name: 'Pasta de Pistacho Pura', price: 15.0, packageSize: 250, unit: 'g' },
  { id: '34', name: 'Yogur Griego Natural', price: 2.0, packageSize: 500, unit: 'g' },
  { id: '35', name: 'Miel de Flores', price: 4.0, packageSize: 500, unit: 'g' },
  { id: '36', name: 'Nueces', price: 5.0, packageSize: 200, unit: 'g' },
  { id: '37', name: 'Leche de Coco', price: 2.5, packageSize: 400, unit: 'ml' },
  { id: '38', name: 'Lima', price: 1.8, packageSize: 4, unit: 'unit' },
  { id: '39', name: 'Harina de Repostería', price: 1.4, packageSize: 1000, unit: 'g' },
  { id: '40', name: 'Bicarbonato Sódico', price: 1.0, packageSize: 200, unit: 'g' },
  { id: '41', name: 'Levadura Química (Polvo de hornear)', price: 1.2, packageSize: 100, unit: 'g' },
  { id: '42', name: 'Azúcar Moreno', price: 2.0, packageSize: 500, unit: 'g' },
  { id: '43', name: 'Mantequilla Salada', price: 3.6, packageSize: 250, unit: 'g' },
  { id: '44', name: 'Avellana Tostada Molida', price: 5.5, packageSize: 200, unit: 'g' },
  { id: '45', name: 'Canela en Polvo', price: 1.5, packageSize: 50, unit: 'g' },
  { id: '46', name: 'Manzana Golden', price: 2.0, packageSize: 1000, unit: 'g' },
  { id: '47', name: 'Masa de Hojaldre', price: 3.0, packageSize: 500, unit: 'g' },
  { id: '48', name: 'Queso Mascarpone', price: 4.0, packageSize: 250, unit: 'g' },
  { id: '49', name: 'Bizcochos de Soletilla (Savoiardi)', price: 2.5, packageSize: 200, unit: 'g' },
  { id: '50', name: 'Amaretto', price: 12.0, packageSize: 700, unit: 'ml' },
  { id: '51', name: 'Ron Añejo', price: 15.0, packageSize: 700, unit: 'ml' },
  { id: '52', name: 'Naranja', price: 1.8, packageSize: 1000, unit: 'g' },
  { id: '53', name: 'Agua de Azahar', price: 2.5, packageSize: 100, unit: 'ml' },
  { id: '54', name: 'Fruta Confitada', price: 4.0, packageSize: 250, unit: 'g' },
  { id: '55', name: 'Almendra Laminada', price: 4.5, packageSize: 150, unit: 'g' },
  { id: '56', name: 'Chocolate Ruby', price: 8.0, packageSize: 250, unit: 'g' },
  { id: '57', name: 'Puré de Mango', price: 6.5, packageSize: 500, unit: 'g' },
  { id: '58', name: 'Pasta de Vainilla', price: 15.0, packageSize: 50, unit: 'g' },
  { id: '59', name: 'Isomalt', price: 8.0, packageSize: 250, unit: 'g' },
  { id: '60', name: 'Colorante Alimentario (varios)', price: 3.0, packageSize: 10, unit: 'g' },
  { id: '61', name: 'Puré de Yuzu', price: 12.0, packageSize: 250, unit: 'g' },
  { id: '62', name: 'Praliné de Avellana', price: 9.0, packageSize: 250, unit: 'g' },
  { id: '63', name: 'Chocolate Dulcey (Caramelizado)', price: 7.0, packageSize: 250, unit: 'g' },
  { id: '64', name: 'Pimienta de Sichuan', price: 4.0, packageSize: 20, unit: 'g' },
  { id: '65', name: 'Cardamomo Verde', price: 3.5, packageSize: 20, unit: 'g' },
  { id: '66', name: 'Anís Estrellado', price: 2.0, packageSize: 20, unit: 'g' },
  { id: '67', name: 'Puré de Lichi', price: 9.0, packageSize: 500, unit: 'g' },
  { id: '68', name: 'Agua de Rosas', price: 4.0, packageSize: 100, unit: 'ml' },
  { id: '69', name: 'Té Matcha (Calidad Ceremonial)', price: 18.0, packageSize: 30, unit: 'g' },
  { id: '70', name: 'Sésamo Negro Tostado', price: 3.0, packageSize: 100, unit: 'g' },
  { id: '71', name: 'Haba Tonka', price: 10.0, packageSize: 5, unit: 'unit' },
  { id: '72', name: 'Praliné de Pistacho', price: 12.0, packageSize: 250, unit: 'g' },
  { id: '73', name: 'Puré de Cereza', price: 7.0, packageSize: 500, unit: 'g' },
  { id: '74', name: 'Kirsch (Licor de Cereza)', price: 18.0, packageSize: 700, unit: 'ml' },
  { id: '75', name: 'Flor de Sal', price: 3.0, packageSize: 125, unit: 'g' },
  { id: '76', name: 'Pimienta Rosa', price: 4.0, packageSize: 20, unit: 'g' },
  { id: '77', name: 'Puré de Coco', price: 4.0, packageSize: 400, unit: 'ml' },
  { id: '78', name: 'Ron de Coco (Malibú)', price: 13.0, packageSize: 700, unit: 'ml' },
  { id: '79', name: 'Puré de Albaricoque', price: 5.5, packageSize: 500, unit: 'g' },
  { id: '80', name: 'Romero Fresco', price: 1.5, packageSize: 20, unit: 'g' },
  { id: '81', name: 'Jengibre Fresco', price: 1.0, packageSize: 100, unit: 'g' },
  { id: '82', name: 'Menta Fresca', price: 1.5, packageSize: 20, unit: 'g' },
  { id: '83', name: 'Manteca de Cacao', price: 10.0, packageSize: 200, unit: 'g' },
  { id: '84', name: 'Leche en Polvo Desnatada', price: 4.0, packageSize: 500, unit: 'g' },
  { id: '85', name: 'Dextrosa', price: 5.0, packageSize: 500, unit: 'g' },
  { id: '86', name: 'Neutro para Helados (Estabilizante)', price: 15.0, packageSize: 100, unit: 'g' },
  { id: '87', name: 'Aceite de Oliva Virgen Extra (Suave)', price: 6.0, packageSize: 750, unit: 'ml' },
  { id: '88', name: 'Tomillo Fresco', price: 1.5, packageSize: 20, unit: 'g' },
  { id: '89', name: 'Queso de Cabra (Rulo)', price: 4.0, packageSize: 200, unit: 'g' },
  { id: '90', name: 'Mermelada de Higo', price: 3.0, packageSize: 250, unit: 'g' },
  { id: '91', name: 'Wasabi en Pasta', price: 3.5, packageSize: 43, unit: 'g' },
  { id: '92', name: 'Cerveza Negra (Stout)', price: 2.5, packageSize: 330, unit: 'ml' },
  { id: '93', name: 'Whisky (Ahumado tipo Islay)', price: 25.0, packageSize: 700, unit: 'ml' },
  { id: '94', name: 'Té Earl Grey', price: 3.0, packageSize: 20, unit: 'unit' },
  { id: '95', name: 'Lavanda Seca (Uso culinario)', price: 4.0, packageSize: 20, unit: 'g' },
  { id: '96', name: 'Pailleté Feuilletine', price: 8.0, packageSize: 250, unit: 'g' },
  { id: '97', name: 'Tahini (Pasta de Sésamo)', price: 4.5, packageSize: 300, unit: 'g' },
  { id: '98', name: 'Castañas en Almíbar', price: 6.0, packageSize: 400, unit: 'g' },
  { id: '99', name: 'Aguacate', price: 3.0, packageSize: 2, unit: 'unit' },
  { id: '100', name: 'Sirope de Arce', price: 7.0, packageSize: 250, unit: 'ml' },
  { id: '101', name: 'Uvas Rojas sin Semilla', price: 3.0, packageSize: 500, unit: 'g' },
  { id: '102', name: 'Pera Conferencia', price: 2.5, packageSize: 1000, unit: 'g' },
  { id: '103', name: 'Queso Gorgonzola', price: 4.5, packageSize: 150, unit: 'g' },
  { id: '104', name: 'Miso Blanco (Shiromiso)', price: 5.0, packageSize: 300, unit: 'g' },
  { id: '105', name: 'Chile en Polvo (Suave)', price: 1.5, packageSize: 50, unit: 'g' },
  { id: '106', name: 'Foie Gras Micuit', price: 20.0, packageSize: 150, unit: 'g' },
];

export const INITIAL_RECIPES: Recipe[] = [
  // GALLETAS
  {
    id: '1',
    name: 'Galletas con Chips de Chocolate',
    description: 'Clásicas galletas americanas, crujientes por fuera y suaves por dentro.',
    familyId: '1',
    yieldAmount: 24,
    yieldUnit: 'galletas',
    ingredients: [
      { rawMaterialId: '1', quantity: 250, unit: 'g' },
      { rawMaterialId: '42', quantity: 150, unit: 'g' },
      { rawMaterialId: '3', quantity: 125, unit: 'g' },
      { rawMaterialId: '4', quantity: 1, unit: 'unit' },
      { rawMaterialId: '5', quantity: 200, unit: 'g' },
      { rawMaterialId: '7', quantity: 5, unit: 'ml' },
      { rawMaterialId: '40', quantity: 5, unit: 'g' },
    ],
    instructions: [
      'Precalentar el horno a 180°C.',
      'Mezclar la mantequilla pomada con el azúcar hasta obtener una crema.',
      'Añadir el huevo y la vainilla y batir bien.',
      'Incorporar la harina y el bicarbonato y mezclar hasta que se integre.',
      'Añadir los chips de chocolate.',
      'Formar bolas y hornear durante 12-15 minutos.',
    ],
  },
  {
    id: '101',
    name: 'Sablé Bretón',
    description: 'Galleta de mantequilla de origen bretón, arenosa, friable y con un intenso sabor.',
    familyId: '1',
    yieldAmount: 20,
    yieldUnit: 'galletas',
    ingredients: [
      { rawMaterialId: '23', quantity: 80, unit: 'g' },
      { rawMaterialId: '2', quantity: 150, unit: 'g' },
      { rawMaterialId: '43', quantity: 180, unit: 'g' },
      { rawMaterialId: '39', quantity: 250, unit: 'g' },
      { rawMaterialId: '41', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Batir las yemas con el azúcar hasta blanquear.',
      'Añadir la mantequilla en pomada y mezclar hasta integrar.',
      'Incorporar la harina y la levadura tamizadas, mezclar sin trabajar en exceso.',
      'Estirar la masa entre dos papeles de horno a 5mm y enfriar 2 horas.',
      'Cortar con un cortapastas y hornear dentro de aros de emplatar a 170°C durante 15-20 minutos.',
    ],
  },
  {
    id: '121',
    name: 'Cookies de Tahini y Chocolate Negro',
    description: 'Una versión sofisticada de la cookie, con el sabor a nuez del tahini y un toque de sal en escamas.',
    familyId: '1',
    yieldAmount: 18,
    yieldUnit: 'cookies',
    ingredients: [
      { rawMaterialId: '3', quantity: 120, unit: 'g' },
      { rawMaterialId: '97', quantity: 130, unit: 'g' },
      { rawMaterialId: '42', quantity: 200, unit: 'g' },
      { rawMaterialId: '4', quantity: 1, unit: 'unit' },
      { rawMaterialId: '1', quantity: 180, unit: 'g' },
      { rawMaterialId: '40', quantity: 4, unit: 'g' },
      { rawMaterialId: '5', quantity: 150, unit: 'g' },
      { rawMaterialId: '75', quantity: 3, unit: 'g' },
    ],
    instructions: [
      'Batir la mantequilla pomada con el azúcar moreno y el tahini.',
      'Añadir el huevo y batir hasta emulsionar.',
      'Incorporar la harina y el bicarbonato tamizados.',
      'Añadir el chocolate negro troceado.',
      'Refrigerar la masa al menos 1 hora.',
      'Formar bolas, espolvorear con flor de sal y hornear a 180°C por 13-15 minutos.',
    ],
  },
  {
    id: '122',
    name: 'Sablés Diamant de Vainilla y Pimienta Rosa',
    description: 'Elegantes galletas de mantequilla rebozadas en azúcar, con el aroma de la vainilla y el toque floral de la pimienta rosa.',
    familyId: '1',
    yieldAmount: 30,
    yieldUnit: 'galletas',
    ingredients: [
      { rawMaterialId: '3', quantity: 200, unit: 'g' },
      { rawMaterialId: '14', quantity: 80, unit: 'g' },
      { rawMaterialId: '58', quantity: 10, unit: 'g' },
      { rawMaterialId: '1', quantity: 250, unit: 'g' },
      { rawMaterialId: '76', quantity: 5, unit: 'g' },
      { rawMaterialId: '2', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Batir la mantequilla pomada con el azúcar glas y la pasta de vainilla.',
      'Añadir la harina y la pimienta rosa machacada, mezclar hasta formar una masa.',
      'Formar un cilindro con la masa y refrigerar 2 horas.',
      'Rebozar el cilindro en azúcar blanco.',
      'Cortar rodajas de 1 cm de grosor.',
      'Hornear a 170°C durante 12-15 minutos, hasta que los bordes estén dorados.',
    ],
  },
  // PASTELES (ENTREMETS)
  {
    id: '2',
    name: 'Pastel Ópera',
    description: 'Un clásico francés con capas de bizcocho Joconde, crema de mantequilla de café y ganache de chocolate.',
    familyId: '2',
    yieldAmount: 1,
    yieldUnit: 'pastel 20x20cm',
    ingredients: [
        { rawMaterialId: '13', quantity: 125, unit: 'g' },
        { rawMaterialId: '14', quantity: 125, unit: 'g' },
        { rawMaterialId: '4', quantity: 4, unit: 'unit' },
        { rawMaterialId: '39', quantity: 30, unit: 'g' },
        { rawMaterialId: '3', quantity: 30, unit: 'g' },
        { rawMaterialId: '24', quantity: 100, unit: 'g' },
        { rawMaterialId: '2', quantity: 20, unit: 'g' },
        { rawMaterialId: '5', quantity: 150, unit: 'g' },
        { rawMaterialId: '8', quantity: 150, unit: 'ml' },
    ],
    instructions: [
      'Preparar bizcocho Joconde y hornear 3 planchas finas.',
      'Preparar un almíbar de café para calar los bizcochos.',
      'Preparar una crema de mantequilla de café.',
      'Preparar una ganache de chocolate.',
      'Montaje: capa de bizcocho calado, capa de crema de café, capa de bizcocho, capa de ganache, capa de bizcocho, capa de crema de café.',
      'Enfriar y cubrir con un glaseado de chocolate brillante.',
    ],
  },
  {
    id: '103',
    name: 'Fraisier Moderno',
    description: 'Versión actualizada del clásico pastel de fresas, con un bizcocho ligero, cremoso de vainilla y fresas frescas.',
    familyId: '2',
    yieldAmount: 1,
    yieldUnit: 'tarta 18cm',
    ingredients: [
        { rawMaterialId: '8', quantity: 250, unit: 'ml' },
        { rawMaterialId: '58', quantity: 10, unit: 'g' },
        { rawMaterialId: '9', quantity: 3, unit: 'unit' },
        { rawMaterialId: '23', quantity: 60, unit: 'g' },
        { rawMaterialId: '2', quantity: 50, unit: 'g' },
        { rawMaterialId: '10', quantity: 100, unit: 'g' },
        { rawMaterialId: '31', quantity: 300, unit: 'g' },
    ],
    instructions: [
      'Preparar una base de bizcocho genovés o dacquoise.',
      'Preparar un cremoso de vainilla (tipo bavaroise) y enfriar.',
      'Forrar un aro con acetato. Colocar la base de bizcocho.',
      'Cortar fresas por la mitad y colocarlas en la pared del aro.',
      'Rellenar el centro con el cremoso de vainilla y más fresas troceadas.',
      'Alisar la superficie y congelar.',
      'Terminar con un glaseado neutro o un gelificado de fresa.',
    ],
  },
  {
    id: '123',
    name: 'Entremet "Eclipse"',
    description: 'Un pastel moderno que combina la acidez del yuzu, el sabor tostado del sésamo negro y la dulzura del chocolate blanco.',
    familyId: '2',
    yieldAmount: 1,
    yieldUnit: 'pastel 18cm',
    ingredients: [
      { rawMaterialId: '70', quantity: 50, unit: 'g' },
      { rawMaterialId: '61', quantity: 120, unit: 'g' },
      { rawMaterialId: '10', quantity: 250, unit: 'g' },
      { rawMaterialId: '8', quantity: 300, unit: 'ml' },
      { rawMaterialId: '9', quantity: 3, unit: 'unit' },
    ],
    instructions: [
      'Base: sablé bretón de sésamo negro.',
      'Interior: cremoso de yuzu.',
      'Exterior: mousse de chocolate blanco.',
      'Montaje: sobre la base de sablé, colocar un disco de cremoso de yuzu congelado. Cubrir con la mousse de chocolate blanco en un molde.',
      'Congelar el entremet por completo.',
      'Cubrir con un glaseado espejo de color amarillo pálido o un pulverizado de manteca de cacao blanca.',
    ],
  },
  {
    id: '124',
    name: 'Pastel "Forêt-Noire" Revisitado',
    description: 'Una deconstrucción moderna de la Selva Negra, con un bizcocho Sacher, cremoso de chocolate, mousse de Kirsch y gel de cereza.',
    familyId: '2',
    yieldAmount: 1,
    yieldUnit: 'pastel 16cm',
    ingredients: [
      { rawMaterialId: '5', quantity: 200, unit: 'g' },
      { rawMaterialId: '73', quantity: 250, unit: 'g' },
      { rawMaterialId: '74', quantity: 30, unit: 'ml' },
      { rawMaterialId: '8', quantity: 350, unit: 'ml' },
      { rawMaterialId: '9', quantity: 4, unit: 'unit' },
    ],
    instructions: [
      'Base: Bizcocho Sacher.',
      'Interior: un disco de gelificado de cereza y Kirsch.',
      'Capa 1: Cremoso de chocolate negro 70%.',
      'Capa 2: Mousse ligera de chocolate blanco y Kirsch.',
      'Montar en un aro por capas y congelar.',
      'Decorar con un pulverizado efecto terciopelo rojo oscuro y virutas de chocolate.',
    ],
  },
  // PANES
  {
    id: '104',
    name: 'Roscón de Reyes',
    description: 'El dulce tradicional español para el día de Reyes, una masa de brioche aromatizada con cítricos y agua de azahar.',
    familyId: '3',
    yieldAmount: 1,
    yieldUnit: 'roscón grande',
    ingredients: [
      { rawMaterialId: '16', quantity: 400, unit: 'g' },
      { rawMaterialId: '6', quantity: 100, unit: 'ml' },
      { rawMaterialId: '4', quantity: 2, unit: 'unit' },
      { rawMaterialId: '2', quantity: 100, unit: 'g' },
      { rawMaterialId: '3', quantity: 100, unit: 'g' },
      { rawMaterialId: '15', quantity: 20, unit: 'g' },
      { rawMaterialId: '51', quantity: 10, unit: 'ml' },
      { rawMaterialId: '53', quantity: 15, unit: 'ml' },
      { rawMaterialId: '52', quantity: 1, unit: 'unit' },
      { rawMaterialId: '54', quantity: 100, unit: 'g' },
      { rawMaterialId: '55', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Hacer una masa madre o prefermento.',
      'Amasar todos los ingredientes (excepto la decoración) hasta obtener una masa elástica.',
      'Dejar fermentar en bloque hasta que doble su tamaño.',
      'Formar el roscón, introducir la sorpresa y dejar fermentar de nuevo.',
      'Pintar con huevo, decorar con fruta confitada, almendra laminada y azúcar perlado.',
      'Hornear a 170°C durante 20-25 minutos.',
    ],
  },
  {
    id: '125',
    name: 'Babka de Chocolate y Praliné',
    description: 'Un pan trenzado de origen judío, con una masa de brioche suave y un relleno generoso de chocolate y praliné de avellana.',
    familyId: '3',
    yieldAmount: 1,
    yieldUnit: 'babka',
    ingredients: [
      { rawMaterialId: '16', quantity: 500, unit: 'g' },
      { rawMaterialId: '3', quantity: 120, unit: 'g' },
      { rawMaterialId: '4', quantity: 2, unit: 'unit' },
      { rawMaterialId: '2', quantity: 80, unit: 'g' },
      { rawMaterialId: '5', quantity: 150, unit: 'g' },
      { rawMaterialId: '62', quantity: 100, unit: 'g' },
    ],
    instructions: [
      'Preparar una masa de brioche y dejarla fermentar en frío durante la noche.',
      'Estirar la masa en un rectángulo. Untar con praliné y esparcir chips de chocolate.',
      'Enrollar la masa para formar un cilindro. Cortar el cilindro por la mitad a lo largo.',
      'Trenzar las dos mitades, con el corte hacia arriba.',
      'Colocar en un molde de cake y dejar fermentar por segunda vez.',
      'Hornear a 180°C durante 35-40 minutos. Pincelar con almíbar al salir del horno.',
    ],
  },
  // MASAS FRITAS
  {
    id: '7',
    name: 'Churros Tradicionales',
    description: 'Crujientes por fuera, tiernos por dentro. Ideales para mojar en chocolate caliente.',
    familyId: '4',
    yieldAmount: 30,
    yieldUnit: 'churros',
    ingredients: [
        { rawMaterialId: '1', quantity: 250, unit: 'g' },
        { rawMaterialId: '17', quantity: 5, unit: 'g' },
        { rawMaterialId: '6', quantity: 400, unit: 'ml' },
        { rawMaterialId: '26', quantity: 1000, unit: 'ml' },
    ],
    instructions: [
        'Poner a hervir el líquido (agua) con la sal.',
        'Cuando hierva, retirar del fuego y añadir la harina de golpe. Mezclar enérgicamente.',
        'Pasar la masa a una churrera o manga pastelera con boquilla de estrella.',
        'Freír en abundante aceite caliente (190°C) hasta que estén dorados.',
        'Escurrir y rebozar en azúcar.',
    ],
  },
  {
    id: '105',
    name: 'Berlinas (Donuts)',
    description: 'Bollos fritos y esponjosos, similares a los donuts, que se pueden rellenar de crema o mermelada.',
    familyId: '4',
    yieldAmount: 15,
    yieldUnit: 'berlinas',
    ingredients: [
      { rawMaterialId: '16', quantity: 500, unit: 'g' },
      { rawMaterialId: '6', quantity: 200, unit: 'ml' },
      { rawMaterialId: '4', quantity: 2, unit: 'unit' },
      { rawMaterialId: '2', quantity: 60, unit: 'g' },
      { rawMaterialId: '3', quantity: 60, unit: 'g' },
      { rawMaterialId: '15', quantity: 25, unit: 'g' },
      { rawMaterialId: '26', quantity: 1000, unit: 'ml' },
    ],
    instructions: [
      'Amasar todos los ingredientes hasta obtener una masa de brioche suave.',
      'Dejar fermentar hasta que doble su volumen.',
      'Estirar la masa a 1.5 cm de grosor y cortar círculos.',
      'Dejar fermentar las piezas cortadas sobre papel de horno.',
      'Freír en aceite a 170°C, 2 minutos por cada lado.',
      'Escurrir, rebozar en azúcar y rellenar si se desea.',
    ],
  },
  {
    id: '126',
    name: 'Cronuts con Glaseado de Arce',
    description: 'El famoso híbrido entre croissant y donut. Masa hojaldrada frita, crujiente y aireada, cubierta con un glaseado dulce.',
    familyId: '4',
    yieldAmount: 10,
    yieldUnit: 'cronuts',
    ingredients: [
      { rawMaterialId: '16', quantity: 500, unit: 'g' }, // Masa de croissant
      { rawMaterialId: '3', quantity: 300, unit: 'g' },
      { rawMaterialId: '26', quantity: 1000, unit: 'ml' },
      { rawMaterialId: '14', quantity: 200, unit: 'g' },
      { rawMaterialId: '100', quantity: 50, unit: 'ml' },
    ],
    instructions: [
      'Preparar una masa de croissant (ver receta).',
      'Estirar la masa a 2 cm de grosor y enfriar bien.',
      'Cortar discos con un cortador de donuts (con agujero).',
      'Dejar fermentar a temperatura ambiente hasta que estén visiblemente hinchados.',
      'Freír en aceite a 175°C, 90 segundos por cada lado, hasta que estén bien dorados y cocidos.',
      'Escurrir sobre papel absorbente. Dejar enfriar.',
      'Preparar un glaseado mezclando el azúcar glas con el sirope de arce y un poco de agua. Bañar los cronuts.',
    ],
  },
  // BOLLERÍA
  {
    id: '5',
    name: 'Croissant de Mantequilla',
    description: 'El clásico de la bollería francesa, con un hojaldrado perfecto y sabor a mantequilla.',
    familyId: '5',
    yieldAmount: 12,
    yieldUnit: 'croissants',
    ingredients: [
        { rawMaterialId: '16', quantity: 500, unit: 'g' },
        { rawMaterialId: '6', quantity: 250, unit: 'ml' },
        { rawMaterialId: '2', quantity: 60, unit: 'g' },
        { rawMaterialId: '17', quantity: 10, unit: 'g' },
        { rawMaterialId: '15', quantity: 20, unit: 'g' },
        { rawMaterialId: '3', quantity: 300, unit: 'g' },
    ],
    instructions: [
        'Amasar todos los ingredientes excepto 280g de mantequilla, hasta obtener una masa lisa.',
        'Dejar fermentar la masa hasta que doble su volumen.',
        'Desgasificar, estirar en un rectángulo y enfriar.',
        'Preparar el bloque de mantequilla (planchón) y enfriar.',
        'Encerrar la mantequilla en la masa y dar 3 pliegues simples, con reposos en frío de 30 minutos entre cada pliegue.',
        'Estirar la masa final, cortar triángulos, formar los croissants y dejar fermentar.',
        'Pintar con huevo y hornear a 190°C durante 15-20 minutos.',
    ],
  },
  {
    id: '127',
    name: 'New York Roll de Pistacho',
    description: 'La última tendencia en bollería. Masa de croissant enrollada, horneada en un aro para conseguir una forma redonda y crujiente, y rellena de crema de pistacho.',
    familyId: '5',
    yieldAmount: 8,
    yieldUnit: 'rolls',
    ingredients: [
      { rawMaterialId: '16', quantity: 500, unit: 'g' }, // Masa de croissant
      { rawMaterialId: '3', quantity: 300, unit: 'g' },
      { rawMaterialId: '33', quantity: 150, unit: 'g' },
      { rawMaterialId: '10', quantity: 100, unit: 'g' },
      { rawMaterialId: '8', quantity: 100, unit: 'ml' },
    ],
    instructions: [
      'Preparar la masa de croissant hasta el último estirado.',
      'Cortar tiras largas de 3 cm de ancho.',
      'Enrollar las tiras sobre sí mismas y colocar en aros de pastelería engrasados.',
      'Dejar fermentar hasta que la masa llene el aro.',
      'Hornear a 180°C durante 20-25 minutos, colocando una bandeja encima para que no suban en exceso.',
      'Preparar una ganache con el chocolate blanco, la nata y la pasta de pistacho.',
      'Una vez fríos los rolls, hacer un agujero en el lateral y rellenar con la ganache. Decorar al gusto.',
    ],
  },
  // MOUSSES Y CREMOSOS
  {
    id: '4',
    name: 'Mousse de Chocolate Intenso',
    description: 'Mousse aireada y con un profundo sabor a chocolate negro.',
    familyId: '6',
    yieldAmount: 8,
    yieldUnit: 'raciones',
    ingredients: [
        { rawMaterialId: '5', quantity: 200, unit: 'g' },
        { rawMaterialId: '8', quantity: 400, unit: 'ml' },
        { rawMaterialId: '23', quantity: 60, unit: 'g' },
        { rawMaterialId: '2', quantity: 50, unit: 'g' },
    ],
    instructions: [
        'Derretir el chocolate al baño maría.',
        'Hacer una pâte à bombe: batir las yemas mientras se vierte un almíbar a 118°C con el azúcar.',
        'Montar la nata hasta picos suaves y reservar en frío.',
        'Mezclar el chocolate derretido (a 45°C) con la pâte à bombe.',
        'Incorporar una parte de la nata montada para aligerar la mezcla.',
        'Incorporar el resto de la nata con movimientos envolventes.',
        'Repartir en copas y refrigerar mínimo 4 horas.',
    ],
  },
  {
    id: '128',
    name: 'Cremoso de Aguacate y Lima con Chocolate Blanco',
    description: 'Un cremoso vegano sorprendentemente sedoso y refrescante, que no sabe a aguacate pero aprovecha su textura.',
    familyId: '6',
    yieldAmount: 6,
    yieldUnit: 'raciones',
    ingredients: [
      { rawMaterialId: '99', quantity: 2, unit: 'unit' },
      { rawMaterialId: '38', quantity: 2, unit: 'unit' },
      { rawMaterialId: '10', quantity: 150, unit: 'g' },
      { rawMaterialId: '37', quantity: 100, unit: 'ml' },
      { rawMaterialId: '100', quantity: 50, unit: 'ml' },
    ],
    instructions: [
      'Derretir el chocolate blanco con la leche de coco.',
      'Triturar la pulpa de aguacate maduro con el zumo y la ralladura de las limas y el sirope de arce hasta obtener un puré muy fino.',
      'Incorporar el chocolate derretido a la mezcla de aguacate y triturar de nuevo hasta que esté perfectamente emulsionado.',
      'Verter en copas o moldes.',
      'Refrigerar al menos 4 horas. La textura será similar a una panna cotta densa.',
    ],
  },
  // TARTAS
  {
    id: '6',
    name: 'Tarta de Limón y Merengue',
    description: 'Combinación perfecta de base crujiente, crema ácida de limón y merengue italiano dulce y tostado.',
    familyId: '7',
    yieldAmount: 1,
    yieldUnit: 'tarta de 22cm',
    ingredients: [
        { rawMaterialId: '1', quantity: 250, unit: 'g' },
        { rawMaterialId: '3', quantity: 125, unit: 'g' },
        { rawMaterialId: '14', quantity: 100, unit: 'g' },
        { rawMaterialId: '4', quantity: 1, unit: 'unit' },
        { rawMaterialId: '25', quantity: 3, unit: 'unit' },
        { rawMaterialId: '23', quantity: 120, unit: 'g' },
        { rawMaterialId: '2', quantity: 150, unit: 'g' },
        { rawMaterialId: '24', quantity: 100, unit: 'g' },
    ],
    instructions: [
        'Para la masa sablée: mezclar harina, azúcar glas y mantequilla fría (sablage). Añadir huevo y formar una bola sin amasar. Refrigerar.',
        'Estirar la masa, forrar un molde y hornear en blanco a 180°C por 20 min.',
        'Para el curd de limón: mezclar zumo y ralladura de limón, yemas y 150g de azúcar. Cocer al baño maría hasta espesar. Enfriar.',
        'Rellenar la base de tarta horneada con el curd de limón.',
        'Para el merengue italiano: hacer un almíbar a 118°C con 200g de azúcar y un poco de agua. Montar las claras y verter el almíbar en forma de hilo.',
        'Cubrir la tarta con el merengue y dorar con un soplete.',
    ],
  },
  {
    id: '129',
    name: 'Tarta de Queso de Cabra, Higos y Nueces',
    description: 'Una tarta de queso horneada de estilo "cheesecake" pero con un toque salado y gourmet, ideal como postre o incluso entrante.',
    familyId: '7',
    yieldAmount: 1,
    yieldUnit: 'tarta 20cm',
    ingredients: [
      { rawMaterialId: '89', quantity: 300, unit: 'g' },
      { rawMaterialId: '30', quantity: 200, unit: 'g' },
      { rawMaterialId: '8', quantity: 150, unit: 'ml' },
      { rawMaterialId: '4', quantity: 2, unit: 'unit' },
      { rawMaterialId: '35', quantity: 50, unit: 'g' },
      { rawMaterialId: '90', quantity: 100, unit: 'g' },
      { rawMaterialId: '36', quantity: 80, unit: 'g' },
    ],
    instructions: [
      'Preparar una base con galletas trituradas y mantequilla. Prensaren el fondo de un molde.',
      'Batir el queso de cabra con el queso crema, la miel y los huevos hasta obtener una mezcla homogénea.',
      'Incorporar la nata y mezclar suavemente.',
      'Verter la mezcla sobre la base de galleta.',
      'Hornear a 160°C durante 50-60 minutos, hasta que los bordes estén firmes y el centro ligeramente tembloroso.',
      'Dejar enfriar completamente en la nevera (mínimo 6 horas).',
      'Cubrir con la mermelada de higos y decorar con nueces tostadas.',
    ],
  },
  // BIZCOCHOS
  {
    id: '8',
    name: 'Bizcocho Genovés',
    description: 'Bizcocho base muy aireado y flexible, perfecto para tartas enrolladas y como base de postres.',
    familyId: '8',
    yieldAmount: 1,
    yieldUnit: 'plancha de 40x30cm',
    ingredients: [
        { rawMaterialId: '4', quantity: 4, unit: 'unit' },
        { rawMaterialId: '2', quantity: 120, unit: 'g' },
        { rawMaterialId: '1', quantity: 120, unit: 'g' },
        { rawMaterialId: '3', quantity: 30, unit: 'g' },
    ],
    instructions: [
        'Precalentar el horno a 180°C.',
        'Batir los huevos con el azúcar al baño maría hasta que alcancen 45°C.',
        'Retirar del fuego y seguir batiendo con batidora eléctrica hasta que la mezcla triplique su volumen y esté fría (punto de letra).',
        'Derretir la mantequilla y dejarla templar.',
        'Incorporar la harina tamizada con movimientos envolventes.',
        'Añadir la mantequilla derretida y mezclar suavemente.',
        'Extender sobre una bandeja con papel de horno y hornear 10-12 minutos.',
    ],
  },
  {
    id: '130',
    name: 'Bizcocho de Aceite de Oliva y Naranja',
    description: 'Un bizcocho increíblemente húmedo y aromático, con el sabor frutal del aceite de oliva virgen extra y el perfume de la naranja.',
    familyId: '8',
    yieldAmount: 1,
    yieldUnit: 'bizcocho 22cm',
    ingredients: [
      { rawMaterialId: '1', quantity: 250, unit: 'g' },
      { rawMaterialId: '2', quantity: 200, unit: 'g' },
      { rawMaterialId: '4', quantity: 3, unit: 'unit' },
      { rawMaterialId: '87', quantity: 180, unit: 'ml' },
      { rawMaterialId: '52', quantity: 2, unit: 'unit' },
      { rawMaterialId: '41', quantity: 10, unit: 'g' },
      { rawMaterialId: '34', quantity: 125, unit: 'g' },
    ],
    instructions: [
      'Batir los huevos con el azúcar hasta blanquear.',
      'Añadir el yogur, el aceite de oliva, y el zumo y ralladura de las naranjas. Mezclar bien.',
      'Incorporar la harina y la levadura tamizadas, mezclando solo hasta integrar.',
      'Verter en un molde engrasado.',
      'Hornear a 180°C durante 40-45 minutos.',
    ],
  },
  // CREMAS Y RELLENOS
  {
    id: '3',
    name: 'Crema Pastelera Profesional',
    description: 'Una crema pastelera sedosa y estable, base para innumerables postres.',
    familyId: '9',
    yieldAmount: 1000,
    yieldUnit: 'g',
    ingredients: [
        { rawMaterialId: '6', quantity: 500, unit: 'ml' },
        { rawMaterialId: '23', quantity: 100, unit: 'g' },
        { rawMaterialId: '2', quantity: 125, unit: 'g' },
        { rawMaterialId: '27', quantity: 40, unit: 'g' },
        { rawMaterialId: '7', quantity: 5, unit: 'ml' },
        { rawMaterialId: '3', quantity: 50, unit: 'g' },
    ],
    instructions: [
        'Hervir la leche con la vainilla.',
        'Mezclar yemas, azúcar y maicena.',
        'Verter la leche caliente sobre la mezcla de yemas, remover y devolver al fuego.',
        'Cocer sin dejar de remover hasta que espese.',
        'Retirar del fuego y añadir la mantequilla fría en cubos.',
        'Filmar a piel y enfriar rápidamente.',
    ],
  },
  // POSTRES CLÁSICOS
  {
    id: '10',
    name: 'Panna Cotta con Vainilla',
    description: 'Postre italiano de nata cocida, increíblemente suave y sedoso. Un lienzo en blanco para cualquier sabor.',
    familyId: '10',
    yieldAmount: 6,
    yieldUnit: 'raciones',
    ingredients: [
      { rawMaterialId: '8', quantity: 500, unit: 'ml' },
      { rawMaterialId: '2', quantity: 80, unit: 'g' },
      { rawMaterialId: '7', quantity: 10, unit: 'ml' },
      { rawMaterialId: '9', quantity: 3, unit: 'unit' },
    ],
    instructions: [
      'Hidratar las hojas de gelatina en agua fría.',
      'Calentar la nata con el azúcar y la vainilla, sin que llegue a hervir.',
      'Retirar del fuego y disolver la gelatina bien escurrida en la nata caliente.',
      'Verter la mezcla en moldes individuales o copas.',
      'Refrigerar un mínimo de 4 horas o hasta que cuaje por completo.',
      'Servir fría, acompañada de coulis de frutas o caramelo.',
    ],
  },
  {
    id: '131',
    name: 'Canelés de Burdeos',
    description: 'Pequeños pasteles de Burdeos con una corteza caramelizada y crujiente y un interior tierno y cremoso, con sabor a ron y vainilla.',
    familyId: '10',
    yieldAmount: 12,
    yieldUnit: 'canelés',
    ingredients: [
      { rawMaterialId: '6', quantity: 500, unit: 'ml' },
      { rawMaterialId: '3', quantity: 50, unit: 'g' },
      { rawMaterialId: '58', quantity: 10, unit: 'g' },
      { rawMaterialId: '2', quantity: 250, unit: 'g' },
      { rawMaterialId: '1', quantity: 125, unit: 'g' },
      { rawMaterialId: '4', quantity: 2, unit: 'unit' },
      { rawMaterialId: '51', quantity: 50, unit: 'ml' },
    ],
    instructions: [
      'Hervir la leche con la vainilla y la mantequilla. Dejar infusionar y enfriar.',
      'Mezclar el azúcar y la harina. Añadir los huevos y batir.',
      'Incorporar la leche infusionada y el ron. Mezclar bien.',
      'Dejar reposar la masa en la nevera durante 24 a 48 horas.',
      'Precalentar el horno a 220°C. Rellenar los moldes de canelé (previamente encerados o engrasados).',
      'Hornear 15 minutos a 220°C, luego bajar a 180°C y hornear 45-50 minutos más.',
      'Desmoldar en caliente y dejar enfriar sobre una rejilla.',
    ],
  },
  // HELADOS Y SORBETES
  {
    id: '12',
    name: 'Sorbete de Limón',
    description: 'Refrescante, ácido y ligero. El limpiador de paladar perfecto o un postre ligero ideal.',
    familyId: '11',
    yieldAmount: 1000,
    yieldUnit: 'ml',
    ingredients: [
      { rawMaterialId: '25', quantity: 5, unit: 'unit' },
      { rawMaterialId: '2', quantity: 250, unit: 'g' },
      { rawMaterialId: '21', quantity: 50, unit: 'g' },
      { rawMaterialId: '22', quantity: 25, unit: 'g' },
    ],
    instructions: [
      'Hacer un almíbar calentando 500ml de agua con los azúcares hasta que se disuelvan. Enfriar.',
      'Exprimir los limones para obtener 250ml de zumo y rallar la piel de uno de ellos.',
      'Mezclar el almíbar frío con el zumo y la ralladura de limón.',
      'Mantecar la mezcla en una heladera.',
      'Guardar en el congelador hasta el momento de servir.',
    ],
  },
  {
    id: '132',
    name: 'Helado de Caramelo Salado y Miso',
    description: 'Un helado complejo y adictivo. El caramelo dulce, la sal y el umami del miso blanco crean un sabor único.',
    familyId: '11',
    yieldAmount: 1000,
    yieldUnit: 'ml',
    ingredients: [
      { rawMaterialId: '2', quantity: 180, unit: 'g' },
      { rawMaterialId: '8', quantity: 400, unit: 'ml' },
      { rawMaterialId: '6', quantity: 200, unit: 'ml' },
      { rawMaterialId: '104', quantity: 30, unit: 'g' },
      { rawMaterialId: '43', quantity: 50, unit: 'g' },
      { rawMaterialId: '23', quantity: 80, unit: 'g' },
    ],
    instructions: [
      'Hacer un caramelo en seco con el azúcar.',
      'Calentar la nata y la leche. Desglasar el caramelo con los líquidos calientes, con mucho cuidado.',
      'Disolver el miso en la mezcla caliente.',
      'Hacer una crema inglesa: batir las yemas, verter la mezcla de caramelo y cocer a 82°C.',
      'Retirar del fuego, añadir la mantequilla salada y emulsionar.',
      'Enfriar, madurar 12h y mantecar en heladera.',
    ],
  },
  // MACARONS
  {
    id: '9',
    name: 'Macarons de Frambuesa',
    description: 'Delicados dulces franceses con una cáscara crujiente y un interior suave, rellenos de ganache de frambuesa.',
    familyId: '12',
    yieldAmount: 20,
    yieldUnit: 'macarons',
    ingredients: [
        { rawMaterialId: '13', quantity: 150, unit: 'g' },
        { rawMaterialId: '14', quantity: 150, unit: 'g' },
        { rawMaterialId: '24', quantity: 110, unit: 'g' },
        { rawMaterialId: '2', quantity: 150, unit: 'g' },
        { rawMaterialId: '18', quantity: 100, unit: 'g' },
        { rawMaterialId: '10', quantity: 150, unit: 'g' },
    ],
    instructions: [
        'Mezclar (tant pour tant) la almendra molida y el azúcar glas. Tamizar.',
        'Dividir las claras en dos partes de 55g.',
        'Mezclar una parte de las claras con el tant pour tant para formar una pasta.',
        'Hacer un merengue italiano con la otra mitad de las claras y un almíbar a 118°C con el azúcar granulado y agua.',
        'Incorporar el merengue a la pasta de almendra (macaronage) hasta obtener una textura de lava.',
        'Formar los macarons con una manga sobre un tapete de silicona y dejar secar (croûtage) 30 min.',
        'Hornear a 150°C durante 12-14 minutos.',
        'Para el relleno: calentar el puré de frambuesa y verter sobre el chocolate blanco troceado. Emulsionar y enfriar.',
        'Rellenar los macarons una vez fríos.',
    ],
  },
  {
    id: '133',
    name: 'Macarons de Foie Gras e Higo',
    description: 'Una creación gourmet para paladares atrevidos. El dulzor de la cáscara contrasta con un relleno untuoso y salado.',
    familyId: '12',
    yieldAmount: 20,
    yieldUnit: 'macarons',
    ingredients: [
      { rawMaterialId: '13', quantity: 150, unit: 'g' },
      { rawMaterialId: '14', quantity: 150, unit: 'g' },
      { rawMaterialId: '24', quantity: 110, unit: 'g' },
      { rawMaterialId: '2', quantity: 150, unit: 'g' },
      { rawMaterialId: '106', quantity: 100, unit: 'g' },
      { rawMaterialId: '90', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Preparar las cáscaras de macaron sin colorante.',
      'Para el relleno: atemperar el foie gras y batirlo hasta que esté cremoso.',
      'Rellenar las cáscaras de macaron con el foie gras batido.',
      'En el centro del relleno, colocar una pequeña cantidad de mermelada de higo.',
      'Cerrar el macaron y refrigerar 24 horas antes de servir.',
    ],
  },
  // PETIT FOURS
  {
    id: '13',
    name: 'Éclairs de Café',
    description: 'Finos pastelitos de pasta choux, rellenos de crema pastelera de café y cubiertos con un glaseado brillante.',
    familyId: '13',
    yieldAmount: 15,
    yieldUnit: 'éclairs',
    ingredients: [
      { rawMaterialId: '6', quantity: 250, unit: 'ml' },
      { rawMaterialId: '3', quantity: 100, unit: 'g' },
      { rawMaterialId: '17', quantity: 4, unit: 'g' },
      { rawMaterialId: '1', quantity: 150, unit: 'g' },
      { rawMaterialId: '4', quantity: 4, unit: 'unit' },
      { rawMaterialId: '29', quantity: 10, unit: 'g' },
    ],
    instructions: [
      'Preparar la pasta choux: hervir agua/leche, sal, azúcar y mantequilla. Añadir la harina de golpe y secar la masa al fuego.',
      'Fuera del fuego, añadir los huevos uno a uno hasta obtener una masa lisa (punto de cinta).',
      'Con una manga y boquilla rizada, formar los éclairs sobre una bandeja de horno.',
      'Hornear a 180°C durante 25-30 minutos, hasta que estén inflados y dorados.',
      'Preparar una crema pastelera y añadirle el café soluble disuelto en un poco de leche caliente.',
      'Una vez fríos los éclairs, rellenarlos.',
      'Bañar la parte superior con un fondant o glaseado de café.',
    ],
  },
  {
    id: '102',
    name: 'Financiers de Almendra',
    description: 'Pequeños bizcochos de almendra y mantequilla avellanada (beurre noisette), húmedos y deliciosos.',
    familyId: '13',
    yieldAmount: 18,
    yieldUnit: 'financiers',
    ingredients: [
      { rawMaterialId: '3', quantity: 150, unit: 'g' },
      { rawMaterialId: '24', quantity: 120, unit: 'g' },
      { rawMaterialId: '14', quantity: 180, unit: 'g' },
      { rawMaterialId: '13', quantity: 100, unit: 'g' },
      { rawMaterialId: '39', quantity: 60, unit: 'g' },
    ],
    instructions: [
      'Hacer una mantequilla avellanada (beurre noisette) calentando la mantequilla hasta que adquiera un color tostado y huela a frutos secos. Enfriar.',
      'Mezclar los ingredientes secos: azúcar glas, almendra y harina.',
      'Añadir las claras sin montar y mezclar.',
      'Incorporar la mantequilla avellanada fría y mezclar hasta homogeneizar.',
      'Dejar reposar la masa en frío al menos 2 horas.',
      'Rellenar moldes de financier y hornear a 180°C durante 12-15 minutos.',
    ],
  },
  // GANACHES (NUEVA FAMILIA)
  {
    id: '134',
    name: 'Ganache de Chocolate Negro y Haba Tonka',
    description: 'Una ganache clásica con el toque perfumado y complejo de la haba tonka, con notas de vainilla, almendra y cereza.',
    familyId: '14',
    yieldAmount: 500,
    yieldUnit: 'g',
    ingredients: [
      { rawMaterialId: '5', quantity: 250, unit: 'g' },
      { rawMaterialId: '8', quantity: 250, unit: 'ml' },
      { rawMaterialId: '71', quantity: 1, unit: 'unit' },
      { rawMaterialId: '21', quantity: 25, unit: 'g' },
    ],
    instructions: [
      'Calentar la nata con la glucosa.',
      'Rallar finamente la haba tonka en la nata caliente. Tapar y dejar infusionar durante 15 minutos.',
      'Colar la nata para retirar los restos de haba tonka.',
      'Volver a calentar la nata infusionada hasta que hierva.',
      'Verter la nata caliente sobre el chocolate negro troceado en tres veces, creando una emulsión con una espátula.',
      'Terminar la emulsión con una batidora de mano para un resultado más fino.',
      'Dejar cristalizar a temperatura ambiente o en nevera, filmada a piel.',
    ],
  },
  {
    id: '135',
    name: 'Ganache Montada de Matcha y Sésamo',
    description: 'Ganache ligera y aireada, ideal para rellenos. El sabor herbáceo del té matcha se combina con el dulzor del chocolate blanco y el tostado del sésamo.',
    familyId: '14',
    yieldAmount: 750,
    yieldUnit: 'g',
    ingredients: [
      { rawMaterialId: '10', quantity: 200, unit: 'g' },
      { rawMaterialId: '8', quantity: 500, unit: 'ml' },
      { rawMaterialId: '69', quantity: 10, unit: 'g' },
      { rawMaterialId: '70', quantity: 20, unit: 'g' },
    ],
    instructions: [
      'Picar el chocolate blanco y ponerlo en un bol.',
      'Calentar 200ml de nata. Disolver el té matcha en la nata caliente.',
      'Verter la nata caliente sobre el chocolate en tres veces, creando una emulsión.',
      'Añadir los 300ml de nata fría restantes y el sésamo tostado. Emulsionar con batidora de mano.',
      'Filmar a piel y refrigerar al menos 12 horas.',
      'Al día siguiente, montar con varillas como si fuera nata normal hasta obtener la consistencia deseada.',
    ],
  },
  {
    id: '136',
    name: 'Ganache de Lichi, Rosa y Frambuesa',
    description: 'La combinación clásica de Pierre Hermé (Ispahan). Una ganache frutal y floral, perfecta para macarons o tartas.',
    familyId: '14',
    yieldAmount: 500,
    yieldUnit: 'g',
    ingredients: [
      { rawMaterialId: '56', quantity: 250, unit: 'g' },
      { rawMaterialId: '67', quantity: 100, unit: 'g' },
      { rawMaterialId: '18', quantity: 50, unit: 'g' },
      { rawMaterialId: '68', quantity: 5, unit: 'ml' },
    ],
    instructions: [
      'Picar el chocolate Ruby y ponerlo en un bol.',
      'Calentar los purés de lichi y frambuesa.',
      'Verter los purés calientes sobre el chocolate y emulsionar.',
      'Añadir el agua de rosas y mezclar.',
      'Emulsionar con batidora de mano y dejar cristalizar.',
    ],
  },
  {
    id: '137',
    name: 'Ganache de Caramelo Salado y Whisky',
    description: 'Una ganache potente y compleja para adultos. El dulzor del caramelo se equilibra con la sal y las notas ahumadas del whisky.',
    familyId: '14',
    yieldAmount: 600,
    yieldUnit: 'g',
    ingredients: [
      { rawMaterialId: '2', quantity: 150, unit: 'g' },
      { rawMaterialId: '8', quantity: 200, unit: 'ml' },
      { rawMaterialId: '43', quantity: 100, unit: 'g' },
      { rawMaterialId: '63', quantity: 200, unit: 'g' },
      { rawMaterialId: '93', quantity: 25, unit: 'ml' },
    ],
    instructions: [
      'Hacer un caramelo en seco con el azúcar.',
      'Desglasar con la nata caliente. Cocer hasta disolver el caramelo.',
      'Añadir la mantequilla salada y mezclar.',
      'Verter el caramelo caliente sobre el chocolate Dulcey picado y emulsionar.',
      'Añadir el whisky y volver a emulsionar.',
      'Dejar cristalizar.',
    ],
  },
  {
    id: '138',
    name: 'Ganache de Aceite de Oliva, Tomillo y Limón',
    description: 'Una ganache mediterránea y sorprendente. El chocolate blanco sirve de lienzo para el sabor frutal del aceite y los aromas herbales.',
    familyId: '14',
    yieldAmount: 500,
    yieldUnit: 'g',
    ingredients: [
      { rawMaterialId: '10', quantity: 250, unit: 'g' },
      { rawMaterialId: '8', quantity: 150, unit: 'ml' },
      { rawMaterialId: '87', quantity: 70, unit: 'ml' },
      { rawMaterialId: '88', quantity: 5, unit: 'g' },
      { rawMaterialId: '25', quantity: 1, unit: 'unit' },
    ],
    instructions: [
      'Infusionar la nata caliente con las ramitas de tomillo y la piel de limón durante 20 minutos.',
      'Colar la nata y volver a calentarla hasta que hierva.',
      'Verter sobre el chocolate blanco picado y emulsionar.',
      'Cuando la mezcla esté a unos 35°C, añadir el aceite de oliva y emulsionar con batidora de mano.',
      'Dejar cristalizar.',
    ],
  },
  {
    id: '139',
    name: 'Ganache de Wasabi y Lima',
    description: 'Una ganache atrevida y vibrante. El picante del wasabi se equilibra con la acidez de la lima y el dulzor del chocolate blanco.',
    familyId: '14',
    yieldAmount: 450,
    yieldUnit: 'g',
    ingredients: [
      { rawMaterialId: '10', quantity: 250, unit: 'g' },
      { rawMaterialId: '8', quantity: 150, unit: 'ml' },
      { rawMaterialId: '91', quantity: 10, unit: 'g' },
      { rawMaterialId: '38', quantity: 1, unit: 'unit' },
    ],
    instructions: [
      'Calentar la nata. Disolver la pasta de wasabi en la nata caliente.',
      'Verter sobre el chocolate blanco picado y emulsionar.',
      'Añadir el zumo y la ralladura de la lima y volver a emulsionar.',
      'Dejar cristalizar. Ideal para bombones o rellenos inesperados.',
    ],
  },
];